---
- name: Configure Cisco Router Interfaces
  hosts: 192.168.19.5
  gather_facts: no
  connection: network_cli

  vars:
    interfaces:
      - name: Ethernet2/0
        ip: 192.168.10.1
        mask: 255.255.254.0
      - name: Ethernet2/1
        ip: 192.168.20.1
        mask: 255.255.254.0

  tasks:
    - name: Configure IP addresses on interfaces
      cisco.ios.ios_config:
        lines:
          - ip address {{ item.ip }} {{ item.mask }}
          - no shutdown
        parents: interface {{ item.name }}
      loop: "{{ interfaces }}"

    - name: Save configuration
      cisco.ios.ios_config:
        save_when: changed